hl.on("hyprland.start", function ()
    hl.exec_cmd("xrandr --output " .. Monitor2 .. " --primary")
    hl.exec_cmd("clipse -listen")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("waybar")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("hyprpaper")
end)